import type { Section, Question } from "@/types";

export const sections: Section[] = [
  {
    id: "course-overview",
    title: "Course Overview",
    description: "Tell us about your course's basic information, target audience, and learning objectives.",
    checkpointId: "checkpoint-1",
    questions: [
      {
        id: "course-title",
        type: "text",
        label: "Course Title",
        description: "The official name of your course as it will appear in Canvas.",
        placeholder: "e.g., Introduction to Data Science",
        required: true,
        validation: { minLength: 5, maxLength: 100 },
      },
      {
        id: "course-code",
        type: "text",
        label: "Course Code",
        description: "The course identifier (e.g., CS 101, MATH 2001).",
        placeholder: "e.g., CS 101",
        required: true,
      },
      {
        id: "course-description",
        type: "textarea",
        label: "Course Description",
        description: "A comprehensive description of what the course covers and why it matters.",
        placeholder: "Describe the course content, its relevance, and what makes it valuable for students...",
        required: true,
        validation: { minLength: 100, maxLength: 2000 },
      },
      {
        id: "target-audience",
        type: "textarea",
        label: "Target Audience",
        description: "Who is this course designed for? Include prerequisites, expected background, and student level.",
        placeholder: "e.g., Undergraduate students with basic programming experience, professionals looking to transition into data science...",
        required: true,
        validation: { minLength: 50, maxLength: 500 },
      },
      {
        id: "delivery-format",
        type: "select",
        label: "Delivery Format",
        description: "How will this course be delivered?",
        required: true,
        options: [
          { value: "fully-online", label: "Fully Online (Asynchronous)" },
          { value: "online-synchronous", label: "Online with Synchronous Sessions" },
          { value: "hybrid", label: "Hybrid (Online + In-Person)" },
          { value: "in-person", label: "Primarily In-Person with Online Components" },
        ],
      },
      {
        id: "course-duration",
        type: "select",
        label: "Course Duration",
        description: "How long does the course run?",
        required: true,
        options: [
          { value: "8-weeks", label: "8 Weeks" },
          { value: "10-weeks", label: "10 Weeks (Quarter)" },
          { value: "15-weeks", label: "15-16 Weeks (Semester)" },
          { value: "other", label: "Other" },
        ],
      },
      {
        id: "credit-hours",
        type: "select",
        label: "Credit Hours",
        description: "How many credit hours is this course worth?",
        required: true,
        options: [
          { value: "1", label: "1 Credit" },
          { value: "2", label: "2 Credits" },
          { value: "3", label: "3 Credits" },
          { value: "4", label: "4 Credits" },
          { value: "5", label: "5+ Credits" },
        ],
      },
      {
        id: "learning-objectives",
        type: "textarea",
        label: "Learning Objectives",
        description: "List 4-6 measurable learning objectives. Start each with an action verb (e.g., 'Analyze', 'Design', 'Evaluate'). Put each objective on a new line.",
        placeholder: "1. Analyze datasets using Python and pandas to identify patterns and insights\n2. Design and implement machine learning models for classification and regression tasks\n3. Evaluate model performance using appropriate metrics and validation techniques\n4. Communicate data findings effectively through visualizations and written reports",
        required: true,
        validation: { minLength: 100, maxLength: 2000 },
      },
    ],
  },
  {
    id: "module-structure",
    title: "Module Structure & Content",
    description: "Define the modules/units of your course and the topics covered in each.",
    checkpointId: "checkpoint-2",
    questions: [
      {
        id: "num-modules",
        type: "select",
        label: "Number of Modules",
        description: "How many modules/units will your course have?",
        required: true,
        options: [
          { value: "4", label: "4 Modules" },
          { value: "6", label: "6 Modules" },
          { value: "8", label: "8 Modules" },
          { value: "10", label: "10 Modules" },
          { value: "12", label: "12 Modules" },
          { value: "15", label: "15+ Modules" },
        ],
      },
      {
        id: "module-details",
        type: "textarea",
        label: "Module Titles and Topics",
        description: "List each module with its title and 3-5 key topics. Format: 'Module 1: Title - Topic A, Topic B, Topic C'",
        placeholder: "Module 1: Introduction to Data Science - What is Data Science, The Data Science Process, Tools and Technologies, Career Paths\n\nModule 2: Python Fundamentals - Variables and Data Types, Control Flow, Functions, Libraries Overview\n\nModule 3: Data Manipulation with Pandas - DataFrames, Data Cleaning, Filtering and Selection, Aggregation",
        required: true,
        validation: { minLength: 200, maxLength: 5000 },
      },
      {
        id: "module-pacing",
        type: "textarea",
        label: "Pacing and Sequencing Rationale",
        description: "Explain why you've organized the modules in this order and how long students should spend on each.",
        placeholder: "The course begins with foundational concepts before moving to hands-on skills. Modules 1-3 establish basics (Week 1-3), Modules 4-6 build core competencies (Week 4-6)...",
        required: true,
        validation: { minLength: 100, maxLength: 1500 },
      },
      {
        id: "key-resources",
        type: "textarea",
        label: "Key Resources per Module",
        description: "List required textbooks, readings, videos, or other resources for each module.",
        placeholder: "Module 1: Chapters 1-2 of 'Data Science from Scratch', TED Talk 'The Beauty of Data Visualization'\nModule 2: Python.org tutorial, Codecademy Python track...",
        required: true,
        validation: { minLength: 100, maxLength: 3000 },
      },
      {
        id: "prerequisites-by-module",
        type: "textarea",
        label: "Module Prerequisites/Dependencies",
        description: "Describe which modules depend on others and any internal prerequisites.",
        placeholder: "Module 3 requires completion of Module 2 (Python basics)\nModule 5 builds directly on Module 4's statistical concepts...",
        required: false,
        validation: { maxLength: 1500 },
      },
    ],
  },
  {
    id: "assessment-strategy",
    title: "Assessment Strategy",
    description: "Define how you'll assess student learning: assignments, quizzes, discussions, and grading.",
    checkpointId: "checkpoint-3",
    questions: [
      {
        id: "assignment-types",
        type: "multiselect",
        label: "Assignment Types",
        description: "Select all assignment types you plan to use.",
        required: true,
        options: [
          { value: "essays", label: "Written Essays/Papers" },
          { value: "projects", label: "Projects (Individual or Group)" },
          { value: "problem-sets", label: "Problem Sets/Homework" },
          { value: "labs", label: "Lab Activities" },
          { value: "presentations", label: "Presentations" },
          { value: "case-studies", label: "Case Studies" },
          { value: "reflections", label: "Reflection Journals" },
          { value: "peer-review", label: "Peer Review Activities" },
        ],
      },
      {
        id: "assignment-details",
        type: "textarea",
        label: "Major Assignment Descriptions",
        description: "Describe 3-5 major assignments including their purpose, deliverables, and how they connect to learning objectives.",
        placeholder: "Assignment 1: Data Exploration Project (Weeks 3-4)\nPurpose: Apply data cleaning and visualization skills\nDeliverables: Cleaned dataset, 5+ visualizations, 2-page analysis report\nConnects to Objectives 1 and 4\n\nAssignment 2: Machine Learning Classification Challenge (Weeks 6-8)...",
        required: true,
        validation: { minLength: 200, maxLength: 3000 },
      },
      {
        id: "quiz-structure",
        type: "textarea",
        label: "Quiz/Exam Structure",
        description: "Describe your quiz and exam strategy: frequency, format (multiple choice, short answer, etc.), and coverage.",
        placeholder: "Weekly quizzes (10 questions, multiple choice + 2 short answer) covering that week's module\nMidterm exam (Week 8): Comprehensive, 50 questions covering Modules 1-6\nFinal project presentation replaces traditional final exam",
        required: true,
        validation: { minLength: 100, maxLength: 1500 },
      },
      {
        id: "discussion-prompts",
        type: "textarea",
        label: "Discussion Strategy",
        description: "Describe how you'll use discussions: frequency, expectations, and example prompts.",
        placeholder: "Weekly discussion forums with initial post due Wednesday, two peer responses due Sunday.\n\nExample prompts:\n- Week 2: Share an example of data-driven decision making you've encountered...\n- Week 5: Debate the ethical implications of predictive policing algorithms...",
        required: true,
        validation: { minLength: 100, maxLength: 2000 },
      },
      {
        id: "grading-weights",
        type: "textarea",
        label: "Grading Breakdown",
        description: "List each category and its weight in the final grade.",
        placeholder: "Participation/Discussions: 15%\nWeekly Quizzes: 15%\nHomework Assignments: 20%\nMidterm Project: 20%\nFinal Project: 30%",
        required: true,
        validation: { minLength: 50, maxLength: 500 },
      },
      {
        id: "rubric-criteria",
        type: "textarea",
        label: "Key Rubric Criteria",
        description: "What criteria will you use to evaluate major assignments? List 4-6 criteria with brief descriptions.",
        placeholder: "1. Technical Accuracy - Correct application of concepts and methods\n2. Analysis Depth - Thorough exploration and interpretation of results\n3. Communication - Clear writing and effective visualizations\n4. Creativity - Novel approaches or insights beyond basic requirements\n5. Documentation - Well-organized code with comments and methodology notes",
        required: true,
        validation: { minLength: 100, maxLength: 1500 },
      },
    ],
  },
  {
    id: "engagement-support",
    title: "Engagement & Support",
    description: "Define how you'll welcome students, communicate with them, and provide support.",
    questions: [
      {
        id: "welcome-message",
        type: "textarea",
        label: "Welcome Message",
        description: "Write the welcome message students will see when they first enter the course.",
        placeholder: "Welcome to [Course Name]! I'm excited to have you in this course. Over the next [X] weeks, we'll explore...",
        required: true,
        validation: { minLength: 100, maxLength: 1500 },
      },
      {
        id: "instructor-intro",
        type: "textarea",
        label: "Instructor Introduction",
        description: "Introduce yourself to students: background, teaching philosophy, and what you're passionate about.",
        placeholder: "I'm [Name], and I've been teaching [subject] for [X] years. My background includes... I believe the best learning happens when...",
        required: true,
        validation: { minLength: 100, maxLength: 1500 },
      },
      {
        id: "communication-policy",
        type: "textarea",
        label: "Communication Policies",
        description: "How can students reach you? What are your response time expectations?",
        placeholder: "Office Hours: Tuesdays 2-4pm via Zoom\nEmail Response Time: Within 24 hours on weekdays\nDiscussion Posts: I'll respond to questions within 48 hours\nUrgent Issues: Use [method] for time-sensitive matters",
        required: true,
        validation: { minLength: 100, maxLength: 1000 },
      },
      {
        id: "support-resources",
        type: "textarea",
        label: "Support Resources",
        description: "List academic support resources available to students (tutoring, writing center, tech support, etc.).",
        placeholder: "- University Writing Center: Free tutoring for papers and reports\n- Math Help Lab: Drop-in hours for quantitative support\n- IT Help Desk: Technical issues with Canvas or course tools\n- Academic Advising: Course planning and degree questions",
        required: true,
        validation: { minLength: 50, maxLength: 1000 },
      },
      {
        id: "late-policy",
        type: "textarea",
        label: "Late Work & Extension Policy",
        description: "What is your policy on late submissions and extension requests?",
        placeholder: "Late submissions receive a 10% deduction per day, up to 3 days. After 3 days, assignments receive a zero unless prior arrangements were made. Extensions may be granted for documented emergencies...",
        required: true,
        validation: { minLength: 50, maxLength: 800 },
      },
      {
        id: "accessibility-statement",
        type: "textarea",
        label: "Accessibility Statement",
        description: "How will you accommodate diverse learning needs?",
        placeholder: "I'm committed to making this course accessible to all students. If you have a disability or need accommodations, please contact the Disability Services office and share your accommodation letter with me. I'm happy to discuss...",
        required: true,
        validation: { minLength: 50, maxLength: 800 },
      },
      {
        id: "design-theme",
        type: "select",
        label: "Page Design Theme",
        description: "Choose the visual style for your course pages. All themes use your institution's brand colors.",
        required: true,
        options: [
          { value: "dp-flat-sections-2", label: "Flat Sections - Modern clean design with subtle separators" },
          { value: "dp-rounded-headings", label: "Rounded Headings - Softer visual appearance" },
          { value: "dp-circle-left", label: "Circle Left - Circle accent on left side of headers" },
        ],
      },
    ],
  },
];

export function getSectionById(id: string): Section | undefined {
  return sections.find((s) => s.id === id);
}

export function getQuestionById(id: string): Question | undefined {
  for (const section of sections) {
    const question = section.questions.find((q) => q.id === id);
    if (question) return question;
  }
  return undefined;
}
